routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');
Route::resource('events', 'EventController');

app/User.php
<?php

namespace App;

use Eloquent;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Query\Builder;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Carbon;

/**
 * App\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property int $sex
 * @property int $orient
 * @property int $direct
 * @property int $old
 * @property int $status
 * @property int $role
 * @property int $invited_by_id
 * @property Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 * @property-read DatabaseNotificationCollection|DatabaseNotification[] $notifications
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static Builder|User onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @method static Builder|User withTrashed()
 * @method static Builder|User withoutTrashed()
 * @mixin Eloquent
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    const STATUS_WAIT = 0;
    const STATUS_APPROVE = 1;
    const STATUS_EXP = 2;
    const STATUS_TRINITY = 3;
    const STATUS_GRAND = 4;
    const STATUS_BAN = -1;
    const STATUS_BLOCK = -2;

    const STATUSES = [
        self::STATUS_WAIT => 'waiting',
        self::STATUS_APPROVE => 'approved',
        self::STATUS_EXP => 'exp1',
        self::STATUS_TRINITY => 'trinity',
        self::STATUS_GRAND => 'grand10',
        self::STATUS_BAN => 'banned',
        self::STATUS_BLOCK => 'blocked',
    ];

    const ROLE_DISABLE = 0;
    const ROLE_VIEW = 1;
    const ROLE_USE = 2;
    const ROLE_ADMIN = 4;

    const ROLES = [
        self::ROLE_DISABLE => 'disabled',
        self::ROLE_VIEW => 'viewer',
        self::ROLE_USE => 'user',
        self::ROLE_ADMIN => 'admin',
    ];

    const SEX_MALE = 1;
    const SEX_FEMALE = 2;
    const SEX_SHEMALE = 3;

    const SEX = [
        self::SEX_MALE => 'boy',
        self::SEX_FEMALE => 'girl',
        self::SEX_SHEMALE => 'trans',
    ];

    const ORIENT_HETERO = 1;
    const ORIENT_HOMO = 2;
    const ORIENT_BI = 3;

    const ORIENTS = [
        self::ORIENT_HETERO => 'hetero',
        self::ORIENT_HOMO => 'homo',
        self::ORIENT_BI => 'bi',
    ];

    const DIRECTION_ACTIVE = 1;
    const DIRECTION_PASSIVE = 2;
    const DIRECTION_UNIVERSAL = 3;

    const DIRECTIONS = [
        self::DIRECTION_ACTIVE => 'active',
        self::DIRECTION_PASSIVE => 'passive',
        self::DIRECTION_UNIVERSAL => 'universal',
    ];

    /**
     * @return BelongsTo|User
     */
    public function invitedBy()
    {
        return $this->belongsTo(self::class);
    }

    /**
     * @return HasMany|Collection|User[]
     */
    public function invited()
    {
        return $this->hasMany(self::class, 'id', 'invited_by_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/index.blade.php
<?php
use App\User;
/** @var User[] $users */
?>
@extends('layouts.app')
@section('content')
    @can('approved')

    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('user.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        @can('admin')
                        <th width="10">

                        </th>
                        @endcan
                        <th>
                            {{ trans('user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('user.fields.email') }}
                        </th>
                        <th>
                            {{ trans('user.fields.sex') }}
                        </th>
                        <th>
                            {{ trans('user.fields.old') }}
                        </th>
                        <th>
                            {{ trans('user.fields.status') }}
                        </th>
                        <th>
                            {{ trans('user.fields.role') }}
                        </th>
                        <th>
                            {{ trans('user.fields.invited_by_id') }}
                        </th>
                        @can('admin')
                        <th>
                            &nbsp;
                        </th>
                        @endcan
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($users as $key => $user) { ?>
                        <tr data-entry-id="{{ $user->id }}">
                            @can('admin')
                            <td>
                                <input type="checkbox" name="user[{{ $user->id }}]"/>
                            </td>
                            @endcan
                            <td>
                                {{ $user->name }}
                            </td>
                            <td>
                                {{ $user->email }}
                            </td>
                            <td>
                                <?= User::SEX[$user->sex] ?>
                            </td>
                            <td>
                                {{ $user->old }}
                            </td>
                            <td>
                                <?= User::STATUSES[$user->status] ?>
                            </td>
                            <td>
                                <?= User::ROLES[$user->role] ?>
                            </td>
                            <td>
                                <?= $user->invitedBy->name ?>
                            </td>
                            @can('admin')
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.users.show', $user->id) }}">
                                    {{ trans('global.view') }}
                                </a>
                                <a class="btn btn-xs btn-info" href="{{ route('admin.users.edit', $user->id) }}">
                                    {{ trans('global.edit') }}
                                </a>
                                <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>
                            </td>
                            @endcan
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
{{--            @can('user_delete')--}}

{{--            @endcan--}}
        })

    </script>
@endsection